### PR TITLE
fix(auth): Fetch AWS credentials after Hosted UI login

### LINKED ISSUE #2946: StorageAccessDeniedException when connected with social signIn.
### Description

Hi,

I recently upgraded my amplify libraries to their 1.0 versions, which created **many** problems. Here is one in particular:  

<ins>On IOS:</ins>
When I try to upload a file to S3 using Amplify.Storage.uploadFile() with accessLevel = protected, when connected to Cognito with SocialSignIn (google):
I always receive the following error: StorageAccessDeniedException, S3 access denied when making the API call.  

Yet, when connected with email + password (using Amplify.Auth.signIn()), everything works fine.

<ins>On ANDROID:</ins>
I can't even connect via the google social signIn anymore, the Amplify.Auth.signInWithWebUI(provider: AuthProvider.google) command always produces the following fatal error:

`E/AndroidRuntime( 7685): FATAL EXCEPTION: main
E/AndroidRuntime( 7685): Process: com.***.***, PID: 7685
E/AndroidRuntime( 7685): java.lang.RuntimeException: Unable to resume activity {com.***.***/com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity}: java.lang.IllegalStateException: handleWebUISignInResponse is not supported
E/AndroidRuntime( 7685): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5061)
E/AndroidRuntime( 7685): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5104)
E/AndroidRuntime( 7685): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
E/AndroidRuntime( 7685): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 7685): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime( 7685): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime( 7685): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
`

Did I miss a particular migration step that could have created those problems? 

Cheers,

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

ANDROID:
1. Simply run the following line:   
`Amplify.Auth.signInWithWebUI(
        provider: AuthProvider.google,);`. 

IOS:
1. Connect via `Amplify.Auth.signInWithWebUI(
        provider: AuthProvider.google,);`
2. Upload a file via `Amplify.Storage.uploadFile(localFile: awsFile, key: 'avatar_image',  options: StorageUploadFileOptions(
      accessLevel: StorageAccessLevel.protected,),).result;`

### Screenshots

_No response_

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

### Schema

_No response_

### PR DESCRIPTION
**Pull request by dnys1**
Fixes #2946.

Align logic with username/password login (https://github.com/aws-amplify/amplify-flutter/blob/a010c360376d062eba2c8ac4a01d04a88b555fec/packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/sign_in_state_machine.dart#L539) and refresh AWS credentials upon succesful login.

### CODE REVIEW

**Review by Jordan-Nelson — APPROVED** [review]

File: packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart [hunk 1]
```diff
@@ -193,6 +196,16 @@ class HostedUiStateMachine
...
 
+    // Clear anonymous credentials, if there were any, and fetch authenticated
+    // credentials.
+    if (_identityPoolConfig != null) {
+      await manager.clearCredentials(
+        CognitoIdentityPoolKeys(_identityPoolConfig!),
+      );
+
+      await manager.loadSession();
+    }
```
Comment (NikaHsn) [inline packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart:207]: Q: if check this at the start of the method do we still need to call `manager.loadSession()`?

Comment (dnys1) [reply packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart:207]: Yes, calling `loadSession` after the credentials cleared is important, since `loadSession` will see there are no AWS credentials when there are supposed to be and request them using the user pool tokens we save above.

Comment (NikaHsn) [reply packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart:207]: so if I understood the flow correctly calling `manager.storeCredentials` will store credentials and the load credential store. loading credential store does not `loadSession` and hence we need to call `loadSession` here. is that right?

**Review by NikaHsn — APPROVED** [review]

**Review by NikaHsn — APPROVED** [review]

File: packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart (hunk 1 above)
Comment (dnys1) [reply packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/hosted_ui_state_machine.dart:207]: Yeah, exactly. `storeCredentials` and `clearCredentials` work directly with the credential store. `loadSession` (which calls the `FetchAuthStateMachine`) starts by calling `loadCredentialStore` and makes a decision on what needs to be refreshed based on what's presently saved.
