### PR TITLE
fix(authenticator): Configuration error handling

### LINKED ISSUE #2245: Amplify authenticator UI stuck in loading after error on SignUp
### Description

After receiving an error from my PreSignUp lambda the UI is always stuck in the loading state. More details are below.

My amplify is configured in the state of the main widget like this:

```dart
class _AppState extends State<App> {
  @override
  void initState() {
    super.initState();

    configureAmplify().then((value) {
      // get current user, etc etc
    });
  }
  
  // etc
}
```

And here is my `configureAmplify` function (I use the Hub to remove user data from application, but this is not relevant so I deleted few lines):

```dart
Future<void> configureAmplify() async {
  try {
    await Amplify.addPlugin(AmplifyAuthCognito());

    await Amplify.configure(amplifyconfig);

    Amplify.Hub.listen(HubChannel.Auth, (hubEvent) {
      switch (hubEvent.eventName) {
        case 'SIGNED_IN':
          print('USER IS SIGNED IN');
          break;
        default:
          print('USER EVENT: ${hubEvent.eventName}');
      }
    });

    debugPrint('Successfully configured');
  } on Exception catch (e) {
    debugPrint('Error configuring Amplify: $e');
  }
}
```

After the signup attempt with a social provider, the user is getting an error because of my PreSignUp trigger. I validate a few things to let users log in with social providers, nothing wrong here.

The problem is that after the oauth redirect (for example to `http://localhost:3000/app/?error_description=PreSignUp%20failed%20with%20error%20Invalid%20Email.%20&state=9EKPg3UiN5rv2FTa9VftCHEKxXgkIw5Z&error=invalid_request` when running locally) the amplify isn't configured anymore (logging the message above) and the view (protected by the AuthenticatedView widget) is now in the loading state forever:

```bash
# Error logged by the try {} in the configureAmplify function
Error configuring Amplify: AuthException(message: Invalid Email, recoverySuggestion: null, underlyingException: null)
```

PS.: I'm using MaterialApp.router and configuring the authenticatorBuilder:
```
Authenticator(
      authenticatorBuilder: getAuthenticationBuilder(),
      child: MaterialApp.router(
          // my app configuration
     ),
);
```

PS 2.: my authentication builder is pretty simple, it's modifying only the layout to add a logo and other elements for specific states:
```dart

Widget? Function(BuildContext, AuthenticatorState)? getAuthenticationBuilder() {
  return (BuildContext context, AuthenticatorState state) {
    Widget child;

    switch (state.currentStep) {
      case AuthenticatorStep.confirmResetPassword:
        child = Padding(
          padding: padding,
          child: Column(
            children: [
              _logo(),
              _logoDivider("Change your Password"),
              const ConfirmResetPasswordForm(),
              const Spacer(),
              _dontHaveAccount(state),
            ],
          ),
        );
        break;
      case AuthenticatorStep.resetPassword:
        child = Padding(
          padding: padding,
          child: Column(
            children: [
              _logo(),
              _logoDivider("Reset your Password"),
              ResetPasswordForm(),
              const Spacer(),
              _dontHaveAccount(state),
            ],
          ),
        );
        break;
      case AuthenticatorStep.signIn:
        child = Padding(
          padding: padding,
          child: Column(
            children: [
              _logo(),
              _logoDivider("Sign In with Email/Username"),
              SignInForm(),
              const Spacer(),
              _dontHaveAccount(state),
            ],
          ),
        );
        break;
      case AuthenticatorStep.signUp:
        child = Padding(
          padding: padding,
          child: Column(
            children: [
              // app logo
              _logo(),
              _logoDivider("Enter your details"),
              _signUpForm(),
              const Spacer(),
              _alreadyHaveAnAccount(state)
            ],
          ),
        );
        break;
      default:
        // use default from amplify authenticator package
        return null;
    }

    return Center(
      child: SingleChildScrollView(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(
                maxWidth: ContainerConstants.mediumWidth,
                maxHeight: ContainerConstants.mediumHeight),
            child: Padding(
              padding: EdgeInsets.symmetric(vertical: containerPadding),
              child: Card(
                child: child,
              ),
            ),
          ),
        ),
      ),
    );
  };
}
```

The big problem is that the amplify configure function is always throwing an error after the redirect and I can't just deal with the error myself (for example showing a modal) because the amplify state never changes (even calling `state.changeStep` manually) and my user is never redirected to the login page again.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Configure amplify authenticator like I did
2. Create PreSignUp trigger blocking the user sign up

### Screenshots

image

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

_No response_

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22621.674], locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.18.2
Flutter SDK 3.3.4
tintin_app 1.0.0+1

dependencies:
- amplify_auth_cognito 1.0.0-next.0+5 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_authenticator 1.0.0-next.0+3 [amplify_auth_cognito amplify_core amplify_flutter async aws_common collection flutter flutter_localizations intl meta smithy stream_transform]
- amplify_flutter 1.0.0-next.0+3 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_svg 1.1.5 [flutter meta path_drawing vector_math xml]
- get 4.6.5 [flutter]
- modal_bottom_sheet 2.1.2 [flutter]
- package_info_plus 1.4.3+1 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_strategy 0.2.0 [flutter_web_plugins]

transitive dependencies:
- amplify_auth_cognito_android 1.0.0-next.0+2 [flutter]
- amplify_auth_cognito_dart 0.1.6 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.0+3 [amplify_core flutter]
- amplify_core 1.0.0-next.0+1 [async aws_common aws_signature_v4 collection intl json_annotation logging meta uuid]
- amplify_datastore_plugin_interface 1.0.0-next.0+1 [amplify_core collection flutter meta]
- amplify_flutter_android 1.0.0-next.0 [flutter]
- amplify_flutter_ios 1.0.0-next.0+1 [amplify_core flutter]
- amplify_secure_storage 0.1.1 [amplify_secure_storage_dart async file flutter meta path path_provider]
- amplify_secure_storage_dart 0.1.1 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- async 2.9.0 [collection meta]
- aws_common 0.2.3 [async collection http2 js json_annotation logging meta stream_transform uuid]
- aws_signature_v4 0.2.2 [async aws_common collection convert crypto json_annotation meta path]
- built_collection 5.1.1
- built_value 8.4.1 [built_collection collection fixnum meta]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- convert 3.0.2 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- file 6.1.4 [meta path]
- fixnum 1.0.1
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http2 2.0.0
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- logging 1.0.2
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- oauth2 2.0.0 [collection crypto http http_parser]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.1.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows] 
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- worker_bee 0.1.1 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

Chrome

### OS

Windows

### Deployment Method

Amplify CLI

### CLI Version

10.2.3

### Additional Context

_No response_

### Amplify Config

```
{
  "projectName": "app",
  "version": "3.1",
  "frontend": "flutter",
  "flutter": {
    "config": {
      "ResDir": "./lib/"
    }
  },
  "providers": [
    "awscloudformation"
  ]
}
```

### PR DESCRIPTION
**Pull request by dnys1**
*Issue #, if available:*
Fixes #2245 

*Description of changes:*
- Revamps error handling in `Amplify.configure`
- Handles configuration errors in Authenticator

### CODE REVIEW

File: packages/amplify_authenticator/lib/amplify_authenticator.dart [hunk 1]
```diff
@@ -575,17 +574,24 @@ class _AuthenticatorState extends State<Authenticator> {
...
+        _config = config;
+        _configInitialized = true;
+        _missingConfigValues = missingConfigValues(config);
+      });
+    } on Exception catch (e) {
+      _showExceptionBanner(
+        type: StatusType.error,
+        message: AuthenticatorException(e).message,
+      );
+      await _waitForConfiguration();
```
Comment (ragingsquirrel3) [inline packages/amplify_authenticator/lib/amplify_authenticator.dart:593]: questions: 1) Are we sure we want to catch all exceptions here or are there specific exceptions we would expect here? 2) Could this get into a loop if the same exception gets thrown again on 2nd call?

Comment (dnys1) [reply packages/amplify_authenticator/lib/amplify_authenticator.dart:593]: 1) Yes, since we cannot continue without the config object.
2) No, since the only code paths which throw an exception also reset `asyncConfig`

**Review by ragingsquirrel3 — APPROVED** [review]

File: packages/amplify_core/lib/src/amplify_class.dart [hunk 2]
```diff
@@ -90,21 +90,43 @@ abstract class AmplifyClass {
...
+        );
+      }
+      await configurePlatform(configuration);
+      _configCompleter.complete(amplifyConfig);
+    } on ConfigurationException catch (e, st) {
+      // Complete with the configuration error and reset the completer so
+      // that 1) `configure` can be called again and 2) listeners registered
+      // on `asyncConfig` are notified of the error so they can handle it as
+      // appropriate. For example, the Authenticator listens for `asyncConfig`
+      // to complete before updating the UI.
```
Comment (Jordan-Nelson) [inline packages/amplify_core/lib/src/amplify_class.dart:113]: Appreciate the comments 👍 

My understanding is that we are sort of treating `ConfigurationException` as a fatal exception. That  is, it is thrown in scenarios where we know plugins will not be functional (missing or invalid config). Configure will have to be called again to get plugins into a functional state.

If there are scenarios where an exception may leave plugins in a functional state (not sure what scenario this would be. I guess the hosted UI issues you are resolving?), `ConfigurationException` would not be appropriate. Another exception should be thrown, which will allow `asyncConfig` to complete. Is that understanding correct?

It might be worth adding some of this info to the doc comment for `ConfigurationException`, or maybe the getter for  `asyncConfig`. I could imagine `ConfigurationException` being used incorrectly if it isn't very clear how it should be used.

**Review by Jordan-Nelson — APPROVED** [review]

File: packages/amplify_core/lib/src/amplify_class.dart (hunk 2 above)
Comment (dnys1) [reply packages/amplify_core/lib/src/amplify_class.dart:113]: I almost made it `ConfigurationError extends Error` since it really is unrecoverable. Do you think that would be more clear?

Comment (dnys1) [reply packages/amplify_core/lib/src/amplify_class.dart:114]: Updated to `ConfigurationError` and expanded on its meaning in its docs.
